AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Automatic Database shudown and startup lambda function
Parameters:
  InstanceID:
    Type: String
    Default: testdb
Globals:
  Function:
    MemorySize: 128
    Timeout: 3
    Handler: app.lambdaHandler
    Runtime: nodejs10.x
    Environment:
      Variables:
        INSTANCE_IDENTIFIER:
          Ref: InstanceID
Resources:
  TestDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier:
        Ref: InstanceID
      AllocatedStorage: '5'
      DBInstanceClass: db.t2.micro
      Engine: MySQL
      MasterUsername: admin
      MasterUserPassword: adminPwd
  DBShutDownFunction:
    DependsOn: TestDB
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ahc-auto-aws-db-shutdown-deployment-artifacts/728a6da7463a37a601008488d197babf
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - rds:StopDBInstance
          Resource:
            Fn::Sub: arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:${InstanceID}
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(45 12 ? * MON-FRI *)
  DBStartUpFunction:
    DependsOn: TestDB
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ahc-auto-aws-db-shutdown-deployment-artifacts/84f2503ea6e443c47036d2097814aed9
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - rds:StartDBInstance
          Resource:
            Fn::Sub: arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:${InstanceID}
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(00 13 ? * MON-FRI *)
